
RecipeViewerEvents.removeEntriesCompletely('item', event => {
event.remove('oreberriesreplanted:silver_oreberry')
event.remove('oreberriesreplanted:osmium_oreberry')
event.remove('oreberriesreplanted:uranium_oreberry')
event.remove('oreberriesreplanted:nickel_oreberry')
event.remove('oreberriesreplanted:lead_oreberry')
event.remove('oreberriesreplanted:aluminum_oreberry')
event.remove('oreberriesreplanted:tin_oreberry')
event.remove('oreberriesreplanted:silver_oreberry_bush')
event.remove('oreberriesreplanted:essence_berry_bush')
event.remove('oreberriesreplanted:tin_oreberry_bush')
event.remove('oreberriesreplanted:aluminum_oreberry_bush')
event.remove('oreberriesreplanted:lead_oreberry_bush')
event.remove('oreberriesreplanted:nickel_oreberry_bush')
event.remove('oreberriesreplanted:uranium_oreberry_bush')
event.remove('oreberriesreplanted:osmium_oreberry_bush')
event.remove('oreberriesreplanted:silver_oreberry_juice_bucket')
event.remove('oreberriesreplanted:osmium_oreberry_juice_bucket')
event.remove('oreberriesreplanted:uranium_oreberry_juice_bucket')
event.remove('oreberriesreplanted:nickel_oreberry_juice_bucket')
event.remove('oreberriesreplanted:lead_oreberry_juice_bucket')
event.remove('oreberriesreplanted:aluminum_oreberry_juice_bucket')
event.remove('oreberriesreplanted:tin_oreberry_juice_bucket')
event.remove('create:dough')
event.remove('croptopia:dough')
event.remove('farmersdelight:wheat_dough')

})
RecipeViewerEvents.removeEntries('fluid', event => {
event.remove('oreberriesreplanted:silver_oreberry_juice')
event.remove('oreberriesreplanted:osmium_oreberry_juice')
event.remove('oreberriesreplanted:uranium_oreberry_juice')
event.remove('oreberriesreplanted:nickel_oreberry_juice')
event.remove('oreberriesreplanted:lead_oreberry_juice')
event.remove('oreberriesreplanted:aluminum_oreberry_juice')
event.remove('oreberriesreplanted:tin_oreberry_juice')

})