StartupEvents.registry('block', event => {
  event.create('diamond_berrybush')
    .soundType('crop')
    .hardness(1)
    .resistance(1)
  event.create('platinum_berrybush')
    .soundType('crop')
    .hardness(1)
    .resistance(1)
  event.create('moon_cake_plate_a')
    .soundType('crop')
    .hardness(1)
    .resistance(1)
})