let $Player = Java.loadClass("net.minecraft.world.entity.player.Player")

StartupEvents.registry('item', event => {
  event.create('flying_soul')
  .maxStackSize(1)
  .tooltip("§5§l飞行大师的超音速之魂")
  .tooltip("§d来自异世界的飞行大师之魂无法在这里施展出全部力量")
  .tooltip("§d但即使只是他的一片羽毛")
  .tooltip("§d带动你的飞行也是绰绰有余")
  .tooltip("")
  .tooltip("§6右键时")
  .tooltip("§a允许你进行创造飞行，无饱食度等限制条件")
  .tooltip("§a飞行时再次右键，飞行速度翻倍，最多可翻倍三次")
  .tooltip("§a停止飞行时再次右键以关闭飞行")
  .tooltip("§a创造模式下仍可调整飞行速度，但不能取消飞行状态")
  .tooltip("§7看着很像...但真的是店员鸡的一根羽毛吗？")
  .rarity("epic")
  .tag("curios:charm")
})
StartupEvents.registry('item', event => {
  event.create('detonator')
  .maxStackSize(1)
  .tooltip("§a右键时产生一场爆炸，不会破坏方块")
  .tooltip("§a爆炸的伤害为使用者的血量减一")
  .tooltip("§a根据副手物品更改爆炸伤害")
  .tooltip("§a副手手持TNT会使伤害翻1.5倍")
  .tooltip("§a副手手持混合种子会使爆炸伤害变为二分之一的真实伤害")
  .tooltip("§a有以上附魔时，每次爆炸消耗两个对应物品")
  .tooltip("§a(即使仅剩余一个也可以爆炸)")
  .tooltip("送我一块表，指针倒着走")
  .tooltip("§a由于每次爆炸都会留下你的一滴生命值")
  .tooltip("§a这意味着不使用TNT时，你无法将自己炸死")
  .rarity("epic")
})

StartupEvents.registry('item', event => {
  event.create('tenshis_peach')
  .maxStackSize(64)
  .tooltip("§d闻一下能活千年，吃一口能活万年")
  .tooltip("§d在天上生长只需一天，在地上即使有现代化种植技术也需要很久")
  .tooltip("§d这颗桃子是来自哪里呢？")
  .tooltip("§d是天庭，还是谁的帽子？")
  .tooltip("§5吃下后会给予你非常多的效果——但它生长的很慢！")
   .food(food => { food
      .nutrition(30)
      .saturation(600)
    .effect("minecraft:speed",12000,4,1)
    .effect("minecraft:haste",12000,4,1)
    .effect("minecraft:strength",12000,4,1)
    .effect("minecraft:resistance",12000,2,1)
    .effect("minecraft:fire_resistance",12000,0,1)
    .effect("minecraft:water_breathing",12000,0,1)
    .effect("minecraft:health_boost",12000,7,1)
    .effect("minecraft:regeneration",100,255,1)
    .effect("minecraft:night_vision",12000,0,1)
      .removeEffect('minecraft:poison')
      .alwaysEdible()
      .fastToEat()
  })
})
ItemEvents.modification(event => {
  event.modify('kubejs:tenshis_peach', item => {
    item.rarity = 'EPIC'})

})

StartupEvents.registry('item', event => {
  event.create('corn_ice')
  .maxStackSize(64)
  .tooltip("丰收的证明！")
   .food(food => { food
      .nutrition(3)
      .saturation(1)
    .effect("minecraft:haste",1200,1,1)
      .alwaysEdible()
  })
})
StartupEvents.registry('item', event => {
  event.create('icecream_bowl')
  .maxStackSize(64)
  .tooltip("三种颜色，三倍享受...")
   .food(food => { food
      .nutrition(7)
      .saturation(1)
    .effect("minecraft:fire_resistance",1200,1,1)
      .alwaysEdible()
  })
})
StartupEvents.registry('item', event => {
  event.create('chocolate_cream')
  .maxStackSize(64)
  .tooltip("你跑不过我...?")
   .food(food => { food
      .nutrition(6)
      .saturation(1)
    .effect("minecraft:speed",1200,5,1)
      .alwaysEdible()
  })
})
StartupEvents.registry('item', event => {
  event.create('mr_hat')
  .maxStackSize(64)
  .tooltip("帽子先生的两面")
   .food(food => { food
      .nutrition(6)
      .saturation(1)
    .effect("minecraft:luck",1200,5,1)
      .alwaysEdible()
  })
})
StartupEvents.registry('item', event => {
  event.create('old_ice')
  .maxStackSize(64)
  .tooltip("老年人最爱的经典风味!")
   .food(food => { food
      .nutrition(6)
      .saturation(1)
    .effect("kaleidoscope_end:mint",2400,1,1)
      .alwaysEdible()
  })
})
StartupEvents.registry('item', event => {
  event.create('shimmer_ice')
  .maxStackSize(64)
  .tooltip("微光风味!")
   .food(food => { food
      .nutrition(6)
      .saturation(1)
    .effect("minecraft:night_vision",4800,1,1)
      .alwaysEdible()
  })
})


StartupEvents.registry('item', event => {
  event.create('silver_chicken')
  .maxStackSize(1)
  .tooltip("§l银色店员鸡")
  .tooltip("完成了部分章节的奖励")
  .tooltip("给它一个黄铜及以上的硬币")
  .tooltip("就可以进行一次刮刮乐")
  .rarity("common")
})
StartupEvents.registry('item', event => {
  event.create('golden_chicken')
  .maxStackSize(1)
  .tooltip("§e§l金色店员鸡")
  .tooltip("§e完成了部分章节的奖励")
  .rarity("uncommon")
})
StartupEvents.registry('item', event => {
  event.create('mixed_seed')
  .maxStackSize(64)
  .tooltip("§f一大堆种子和果核混合在了一起，")
  .tooltip("§f它虽然很稀有...但你可以从中分离出大部分你需要的种子，以及果树树苗。")
  .tooltip("§f是的...它有点像异世界的某种种子...")
  .tooltip("§f你确实可以用它合成各种种子...但它真的包含所有种子吗?")
  .tooltip("§f当然没有！远古种子和异世界的种子你是没办法合成的！")
  .tooltip("建议使用动力锯加上过滤器进行处理，过滤器可以使用jei进行过滤，")
  .tooltip("切石机只会显示36种种子，并不能满足所有需求——一共有上百种种子！")
  .tooltip("它本身能种出什么呢...")
})

StartupEvents.registry('item', event => {
  event.create('lich_doll')
  .maxStackSize(1)
  .tooltip("§6把高塔上那只会巫术的骷髅的骨头收集起来打成捆，")
  .tooltip("§6再用普通的骨头给它做些支撑，那只巫妖就可以在这具身体上复活...")
  .tooltip("§6并在普通的骨头也缠绕上它的巫术。")
  .tooltip("§a由于身体不是原来的身体，因此它被弱化了:")
  .tooltip("§a-召唤产生的巫妖王不会制造盾牌")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('naga_feast')
  .maxStackSize(1)
  .tooltip("§2将丛林巨蛇最喜爱的零食装在桶里，")
  .tooltip("§2用它的同类的鳞片作为伪装，")
  .tooltip("§2再吃掉这一桶食物...")
  .tooltip("§2娜迦就会被这盛宴的气味吸引过来。")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('mushroom_meat')
  .maxStackSize(1)
  .tooltip("§4用蘑菇感染牛头人们的首领，")
  .tooltip("§4不断生长的蘑菇甚至可能长出另一只牛头人。")
  .tooltip("§4这只牛头人是原来的牛头人首领，")
  .tooltip("§4还是另一只新的牛头人？")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('hydra_egg')
  .maxStackSize(1)
  .tooltip("§3九头蛇没能诞下子嗣...")
  .tooltip("§3但将其血液注入终末之龙的蛋壳中，")
  .tooltip("§3用血肉作为养分")
  .tooltip("§3一只九头蛇将以此涅槃重生。")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('totem_of_phantom')
  .maxStackSize(1)
  .tooltip("§a往日的幻影中包含了灵魂和记忆，")
  .tooltip("§a将幻影寄托于图腾之上，")
  .tooltip("§a与立场无关，")
  .tooltip("§a即使是普通的铁制装备，骑士的幻影也能重现他们的荣光。")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('ur_ghast_blood_tear')
  .maxStackSize(1)
  .tooltip("§c暮初恶魂与普通恶魂的泪水结合，")
  .tooltip("§c就可以产生一颗巨大的泪晶，")
  .tooltip("§c将它用触手缠住，")
  .tooltip("§c就可以让暮色之初的恶魂重现人间。")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('iceberg_princess')
  .maxStackSize(1)
  .tooltip("§b女王喜欢吃生菜？开什么玩笑！")
  .tooltip("§b即使是科幻小说也不敢轻易采用这样的设定...")
  .tooltip("§b但女王的确喜爱这种生菜，")
  .tooltip("§b以至于能让女王离开城堡，只为了这一口。")
  .rarity("epic")
})
StartupEvents.registry('item', event => {
  event.create('weavers_star')
  .maxStackSize(1)
  .tooltip("§b异世界的天意与本世界的连接之星！")
  .tooltip("§b你可以从来自异世界的材料中获得它，如混合种子！")
  .tooltip("§b我知道...它长得有点像...")
  .rarity("rare")
})
StartupEvents.registry('item', event => {
  event.create('third_eye')
  .maxStackSize(1)
  .tooltip("§4觉妖怪的眼睛")
  .tooltip("§4它可以看到周围的人的各种属性，")
  .tooltip("§4也包括你自己的，这颗眼睛可以看到的东西比你想象中的要多。")
  .tooltip("§4————————————————————————————")
  .tooltip("§4右键可观测自身的各项属性，shift+右键显示周围的玩家的属性")
  .tooltip("§4包含全球信息终端的全部功能：")
  .tooltip("§4显示周围的所有矿石的距离，扫描范围稍微扩大")
  .tooltip("§4与全球信息终端相同：该物品一定不要过于频繁地使用！")
  .rarity("uncommon")
})
StartupEvents.registry('item', event => {
  event.create('ibarakasens_masu')
  .maxStackSize(1)
  .tooltip("§d源源不断产生酒的神奇道具")
  .tooltip("§d啜饮其中的液体会给你...什么效果都有可能")
  .tooltip("§d来自外界的贤者，喝了这酒也许会...")
  .tooltip("§d————————————————————————————")
  .tooltip("§d右键使用后给予四个不同的效果，需要冷却一分钟")
  .tooltip("§d其中如漂浮等持续时大幅影响移动")
  .tooltip("§d或如随机传送等不应该持续的效果不会出现。")
  .tooltip("§d效果可能存在正面效果，也可能存在负面效果")
  .tooltip("§d效果固定为三级，时间固定四分钟")
  .tooltip("§d有可能喝到让人失去任何移动能力等的负面效果")
  .tooltip("§d抽取次数越多越容易抽到这种效果...")
  .rarity("uncommon")
})
StartupEvents.registry('item', event => {
  event.create('diamond_oreberry')
  .maxStackSize(64)
  .tooltip("§7湖面上的妖精常吃的零食")
  .rarity("common")
})
StartupEvents.registry('item', event => {
  event.create('platinum_oreberry')
  .maxStackSize(64)
  .tooltip("§7星辉下的平原浆果")
  .rarity("common")
})
StartupEvents.registry('item', event => {
  event.create('global_information_terminal')
  .maxStackSize(1)
  .tooltip("§a能显示这个世界于你的关系，")
  .tooltip("§a可以显示你的移动速度、当前月相、周围的怪物数量，以及附近的稀有矿石等。")
  .tooltip("§a它并不是很灵敏——")
  .tooltip("§a移动速度需要多次使用才能准确显示正确速度")
  .tooltip("§a周围的矿石只会显示最昂贵的那一个")
  .tooltip("§4该物品一定不要过于频繁地使用！")
})
StartupEvents.registry('item', event => {
  event.create('baguette', 'sword').tier('diamond').attackDamageBaseline(12)
  .maxStackSize(1)
  .maxDamage(24)
  .tooltip("§a民用制式穿甲弹头")
  .tooltip("§a很硬，削尖了可以当剑使")
  .tooltip("§a但手汗会把它泡软，导致它能使用的次数有限")
  .tooltip("你可以试试把它合成为大列巴")
})
