#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Sep 29 00:20:35 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_.Chocapic13_Shaders_edit.zip
