<recipetype:create:sequenced_assembly>.addJsonRecipe("nether_star",
     {type: "create:sequenced_assembly",
     sequence: [{ingredients: [ {item: "minecraft:wither_skeleton_skull"},
     {type: "neoforge:single",
     fluid: "kaleidoscope_grilling:premium_chili_oil",
     amount: 500}],
     results: [{id: "create:unprocessed_obsidian_sheet"}],
     type: "create:filling"},
     {ingredients: [{item: "minecraft:wither_skeleton_skull"},
     {item: "kaleidoscope_nether:star_dust"}],
     results: [{id: "minecraft:wither_skeleton_skull"}],
     type: "create:deploying"},
     {ingredients: [{item: "kaleidoscope_nether:star_dust"},
     {tag: "minecraft:soul_fire_base_blocks"}],
     results: [{id: "minecraft:wither_skeleton_skull"}],
     type: "create:deploying"}],
     transitional_item: {id: "minecraft:wither_skeleton_skull"},
     results: [{id: "minecraft:nether_star"}],
     ingredient: {item: "minecraft:wither_skeleton_skull"}});
<recipetype:create:sequenced_assembly>.addJsonRecipe("precision_mechanism", {sequence: [{type: "create:deploying", ingredients: [{tag: "c:plates/gold"}, {item: "create:cogwheel"}], results: [{id: "create:incomplete_precision_mechanism"}]}, {type: "create:deploying", ingredients: [{item: "create:incomplete_precision_mechanism"}, {item: "create:large_cogwheel"}], results: [{id: "create:incomplete_precision_mechanism"}]}, {type: "create:deploying", ingredients: [{item: "create:incomplete_precision_mechanism"}, {tag: "c:nuggets/iron"}], results: [{id: "create:incomplete_precision_mechanism"}]}], loops: 2, ingredient: {tag: "c:plates/gold"}, type: "create:sequenced_assembly", results: [{id: "create:precision_mechanism", chance: 120.0}], transitional_item: {id: "create:incomplete_precision_mechanism"}});
