
  <recipetype:extradelight:vat>.addJsonRecipe("miso_paste_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:soybeans/cooked"}, {tag: "c:cooked_rice"}, {tag: "c:soybeans/cooked"}, {tag: "c:cooked_rice"}, {tag: "c:soybeans/cooked"}, {tag: "c:cooked_rice"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 4800, lid: false}, {time: 33600, ingredient: {item: "extradelight:yeast"}, lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 6}, result: {id: "extradelight:miso_paste_item", count: 6}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("naem_moo_but_with_dripleaf", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:pork/ground/raw"}, {tag: "extradelight:processed/garlic"}, {tag: "c:cooked_rice"}, {tag: "extradelight:processed/chili"}], stage_ingredients: [{time: 6000, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:big_dripleaf", count: 2}, result: {id: "extradelight:naem_moo_item", count: 2}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("naem_moo_item", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:pork/ground/raw"}, {tag: "extradelight:processed/garlic"}, {tag: "c:cooked_rice"}, {tag: "extradelight:processed/chili"}], stage_ingredients: [{time: 6000, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:lily_pad", count: 2}, result: {id: "extradelight:naem_moo_item", count: 2}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("apple_cider_vinegar", {type: "extradelight:vat", stages: 2, ingredients: [{item: "minecraft:sugar"}], stage_ingredients: [{ingredient: {item: "extradelight:yeast"}, time: 3600, lid: true}, {time: 8400, ingredient: [], lid: false}], usedItem: {id: "minecraft:glass_bottle", count: 4}, result: {id: "extradelight:vinegar", count: 4}, fluids: {fluid: "extradelight:apple_cider_fluid", amount: 1000}});
  <recipetype:extradelight:vat>.addJsonRecipe("fish_sauce_item", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:foods/raw_fish"}], stage_ingredients: [{time: 33600, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:fish_sauce_item", count: 1}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("gherkins_block_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:crops/cucumber"}, {tag: "c:crops/cucumber"}, {tag: "c:crops/cucumber"}, {tag: "c:crops/cucumber"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 1200, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:gherkins_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("hot_sauce_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "extradelight:processed/chili"}, {tag: "extradelight:processed/garlic"}, {tag: "extradelight:processed/onion"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 1200, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 4}, result: {id: "extradelight:hot_sauce_item", count: 4}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("kimchi_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "extradelight:processed/cabbage"}, {tag: "extradelight:processed/cabbage"}, {tag: "extradelight:processed/ginger"}, {tag: "extradelight:processed/garlic"}, {tag: "c:chili/powder"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 700, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:bowl", count: 2}, result: {id: "extradelight:kimchi_item", count: 2}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("miso_paste_item_1", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:soybeans/cooked"}, {item: "farmersdelight:cooked_rice"}, {tag: "c:soybeans/cooked"}, {item: "farmersdelight:cooked_rice"}, {tag: "c:soybeans/cooked"}, {item: "farmersdelight:cooked_rice"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 4800, lid: false}, {time: 33600, ingredient: {item: "extradelight:yeast"}, lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 6}, result: {id: "extradelight:miso_paste_item", count: 6}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("naem_moo_but_with_dripleaf_1", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:pork/ground/raw"}, {tag: "extradelight:processed/garlic"}, {item: "farmersdelight:cooked_rice"}, {tag: "extradelight:processed/chili"}], stage_ingredients: [{time: 6000, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:big_dripleaf", count: 2}, result: {id: "extradelight:naem_moo_item", count: 2}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("naem_moo_item_1", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:pork/ground/raw"}, {tag: "extradelight:processed/garlic"}, {item: "farmersdelight:cooked_rice"}, {tag: "extradelight:processed/chili"}], stage_ingredients: [{time: 6000, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:lily_pad", count: 2}, result: {id: "extradelight:naem_moo_item", count: 2}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("natto_item", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:soybeans/cooked"}], stage_ingredients: [{time: 3600, ingredient: {item: "extradelight:yeast"}, lid: true}], usedItem: {id: "minecraft:bowl", count: 1}, result: {id: "extradelight:natto_item", count: 1}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_beets_block_item", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "extradelight:processed/beetroot"}, {tag: "extradelight:processed/beetroot"}, {tag: "extradelight:processed/beetroot"}, {tag: "extradelight:processed/beetroot"}, {item: "minecraft:sugar"}], stage_ingredients: [{time: 8400, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_beets_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_carrots_block_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:crops/carrot"}, {tag: "c:crops/carrot"}, {tag: "c:crops/carrot"}, {tag: "c:crops/carrot"}], stage_ingredients: [{ingredient: [], time: 8400, lid: true}, {time: 3600, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_carrots_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_eggs_block_item", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:eggs/boiled"}, {tag: "c:eggs/boiled"}, {tag: "c:eggs/boiled"}, {tag: "c:eggs/boiled"}, {item: "minecraft:sugar"}], stage_ingredients: [{time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_eggs_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_fish_block_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:foods/safe_raw_fish"}, {tag: "c:foods/safe_raw_fish"}, {tag: "c:foods/safe_raw_fish"}, {tag: "c:foods/safe_raw_fish"}, {item: "minecraft:sugar"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 1200, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_fish_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_ginger_block_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:ginger/sliced"}, {tag: "c:ginger/sliced"}, {tag: "c:ginger/sliced"}, {tag: "c:ginger/sliced"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 100, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_ginger_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_onions_block_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:crops/onion"}, {tag: "c:crops/onion"}, {tag: "c:crops/onion"}, {tag: "c:crops/onion"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 1200, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_onions_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_rinds_block_item", {type: "extradelight:vat", stages: 2, ingredients: [{item: "extradelight:melon_rind"}, {item: "extradelight:melon_rind"}, {item: "extradelight:melon_rind"}, {item: "extradelight:melon_rind"}, {tag: "extradelight:sweetener"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 1200, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_rinds_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("pickled_sausage_block_item", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:sausage/cooked"}, {tag: "c:sausage/cooked"}, {tag: "c:sausage/cooked"}, {tag: "c:sausage/cooked"}], stage_ingredients: [{time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:pickled_sausage_block_item", count: 1}, fluids: {fluid: "extradelight:vinegar_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("preserved_lemons_block_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "extradelight:processed/lemon"}, {tag: "extradelight:processed/lemon"}, {tag: "extradelight:processed/lemon"}, {tag: "extradelight:processed/lemon"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 1200, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:preserved_lemons_block_item", count: 1}, fluids: {fluid: "extradelight:lemon_juice_fluid", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("sauerkraut_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "extradelight:processed/cabbage"}, {tag: "extradelight:processed/cabbage"}], stage_ingredients: [{ingredient: {tag: "c:salt"}, time: 100, lid: false}, {time: 8400, ingredient: [], lid: true}], usedItem: {id: "minecraft:bowl", count: 2}, result: {id: "extradelight:sauerkraut_item", count: 2}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("soaked_soybeans_item", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:crops/soybean"}], stage_ingredients: [{time: 1200, ingredient: [], lid: true}], usedItem: {id: "minecraft:bowl", count: 1}, result: {id: "extradelight:soaked_soybeans_item", count: 1}, fluids: {fluid: "minecraft:water", amount: 1000}});
  <recipetype:extradelight:vat>.addJsonRecipe("soy_sauce_item", {type: "extradelight:vat", stages: 2, ingredients: [{tag: "c:soybeans/cooked"}, {tag: "c:foods/cooked_wheat_seeds"}], stage_ingredients: [{ingredient: {item: "extradelight:yeast"}, time: 3600, lid: true}, {time: 33600, ingredient: {tag: "c:salt"}, lid: true}], usedItem: {id: "minecraft:glass_bottle", count: 1}, result: {id: "extradelight:soy_sauce_item", count: 1}, fluids: {fluid: "minecraft:water", amount: 250}});
  <recipetype:extradelight:vat>.addJsonRecipe("vinegar", {type: "extradelight:vat", stages: 2, ingredients: [{children: [{tag: "c:fruit"}, {tag: "c:crops/sugar_cane"}, {item: "minecraft:sugar"}, {tag: "c:crops/wheat"}, {tag: "c:crops/rice"}], type: "neoforge:compound"}, {item: "minecraft:sugar"}], stage_ingredients: [{ingredient: {item: "extradelight:yeast"}, time: 3600, lid: true}, {time: 8400, ingredient: [], lid: false}], usedItem: {id: "minecraft:glass_bottle", count: 4}, result: {id: "extradelight:vinegar", count: 4}, fluids: {fluid: "minecraft:water", amount: 1000}});
  <recipetype:extradelight:vat>.addJsonRecipe("yeast", {type: "extradelight:vat", stages: 1, ingredients: [{tag: "c:fruit"}], stage_ingredients: [{time: 8400, ingredient: {item: "extradelight:yeast"}, lid: false}], usedItem: {id: "minecraft:glass_bottle", count: 16}, result: {id: "extradelight:yeast", count: 16}, fluids: {fluid: "minecraft:water", amount: 1000}});

